
DROP TABLE IF EXISTS operation;

CREATE TABLE operation (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id Integer,
    operation_date VARCHAR(255),
    currency_from VARCHAR(255),
    currency_to VARCHAR(255),
    amount_from numeric(10,2),
    amount_to numeric(10,2)
);
