package challenger.com.br.config;

import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.r2dbc.core.DatabaseClient;

import java.io.IOException;

@Configuration
public class AppDBConfiguration {

    @Bean
    public ApplicationRunner init(DatabaseClient client) throws IOException {
        return args ->
            client.sql(
                "DROP TABLE IF EXISTS operation;\n" +
                    "\n" +
                    "CREATE TABLE operation (\n" +
                    "    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                    "    user_id Integer,\n" +
                    "    operation_date VARCHAR(255),\n" +
                    "    currency_from VARCHAR(255),\n" +
                    "    currency_to VARCHAR(255),\n" +
                    "    rate numeric(10,2),\n" +
                    "    amount_from numeric(10,2),\n" +
                    "    amount_to numeric(10,2)\n" +
                ");\n"
            ).fetch().first().subscribe();
    }

}
